# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: presto.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpresto.proto\x12\x06presto\"\x8c\x01\n\x12GrpcSerializedPage\x12\x12\n\nsliceBytes\x18\x01 \x01(\x0c\x12\x15\n\rpositionCount\x18\x02 \x01(\x12\x12\x1f\n\x17uncompressedSizeInBytes\x18\x03 \x01(\x12\x12\x18\n\x10pageCodecMarkers\x18\x04 \x01(\x0c\x12\x10\n\x08\x63hecksum\x18\x05 \x01(\x12\x32V\n\rPrestoService\x12\x45\n\x0bProcessPage\x12\x1a.presto.GrpcSerializedPage\x1a\x1a.presto.GrpcSerializedPageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'presto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRPCSERIALIZEDPAGE']._serialized_start=25
  _globals['_GRPCSERIALIZEDPAGE']._serialized_end=165
  _globals['_PRESTOSERVICE']._serialized_start=167
  _globals['_PRESTOSERVICE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
